### ISSUE TITLE
example17.cpp compile on most compilers

### ISSUE THREAD

**Issue by GregKon** [boostorg/safe_numerics#96]
Hi

example 17 does compile on most compilers where sizeof(int) == sizeof(long), e.g.: gcc 9.2 32bits, msvc in 32 bit mode and most of cross compilers for embedded (where 64bits arch is not common).

The simplest fix will be use "long long".
```
using safe_t = safe<long long, native, loose_trap_policy>;
```

**Comment by robertramey** [comment]
I did find that the example was never used in the documentation so I could have just eliminated it.  But I still think it's interesting.  Perhaps it should be migrated to tests or perhaps this is an indicator that documentation needs some more information.  In any case I alter the example so that it illustrates what it's supposed to.
